FROM mcr.microsoft.com/playwright:v1.48.0-jammy

WORKDIR /app

# Install Node dependencies
COPY package*.json ./
RUN npm ci

# Copy application code
COPY . .

# The actual test command will be provided by docker-compose
CMD ["npx", "playwright", "test"]